#volumes:
#  griddb:

services:

  griddb-server:
    build:
      context: griddb-server
      dockerfile: Dockerfile
    container_name: griddb-server
    user: root
    expose:
      - '10001'
    environment:
      NOTIFICATION_MEMBER: 1
      GRIDDB_CLUSTER_NAME: myCluster
    healthcheck:
        test: ["CMD", "gs_sh"]
        interval: 30s
        timeout: 10s
        retries: 5


  census-analysis: 
    build:
      context: census-analysis
      dockerfile: Dockerfile
    container_name: census-analysis
    profiles:
      - donotstart
    depends_on:
      griddb-server:
        condition: service_healthy
