services:
  griddb-server:
    build:
      context: griddb-server
      dockerfile: Dockerfile
    container_name: griddb-server
    user: root
    expose:
      - '10001'
      - '10010'
      - '10020'
      - '10040'
      - '20001'
      - '41999'
    environment:
      GRIDDB_CLUSTER_NAME: myCluster
    healthcheck:
      test: ["CMD", "gs_stat", "-u", "admin/admin"]
      interval: 120s
      timeout: 120s
      retries: 5
    networks:
      - census-master5_default

  census-analysis:
    build:
      context: census-analysis
      dockerfile: Dockerfile
    container_name: census-analysis
    depends_on:
      - griddb-server
    ports:
      - "3000:3000"
    networks:
      - census-master5_default

networks:
  census-master5_default:
    external: true
